export const matches = [
  {
    id: 1,
    team1: "/GNG.png",
    team2: "/foxgaming.png",
    game: "/lol.png",
    gameName: "lol",
    time: "23 may , 7pm (GMT+1)",
    twitchName: "TWITCH.TV/LOLESPORTS_AR",
    twitchUrl: "https://www.twitch.tv/lolesports_ar",
  },
  {
    id: 2,
    team1: "/GNG.png",
    team2: "/twisted.png",
    game: "/lol.png",
    gameName: "lol",
    time: "24 may , 8pm (GMT+1)",
    twitchName: "TWITCH.TV/LOLESPORTS_AR",
    twitchUrl: "https://www.twitch.tv/lolesports_ar",
  },
  {
    id: 3,
    team1: "/GNG.png",
    team2: "/anubis.png",
    game: "/lol.png",
    gameName: "lol",
    time: "30 may , 9pm (GMT+1)",
    twitchName: "TWITCH.TV/LOLESPORTS_AR",
    twitchUrl: "https://www.twitch.tv/lolesports_ar",
  },
  {
    id: 4,
    team1: "/GNG.png",
    team2: "/raad.png",
    game: "/lol.png",
    gameName: "lol",
    time: "31 may , 6pm (GMT+1)",
    twitchName: "TWITCH.TV/LOLESPORTS_AR",
    twitchUrl: "https://www.twitch.tv/lolesports_ar",
  },
  
  {
    id: 5,
    team1: "/GNG.png",
    team2: "/one-more.png",
    game: "/lol.png",
    gameName: "lol",
    time: "5 june , 7pm (GMT+1)",
    twitchName: "TWITCH.TV/LOLESPORTS_AR",
    twitchUrl: "https://www.twitch.tv/lolesports_ar",
  },
  {
    id: 6,
    team1: "/GNG.png",
    team2: "/Geekay.png",
    game: "/lol.png",
    gameName: "lol",
    time: "6 june , 9pm (GMT+1)",
    twitchName: "TWITCH.TV/LOLESPORTS_AR",
    twitchUrl: "https://www.twitch.tv/lolesports_ar",
  },
  {
    id: 7,
    team1: "/GNG.png",
    team2: "/Nigma.png",
    game: "/lol.png",
    gameName: "lol",
    time: "7 june , 9pm (GMT+1)",
    twitchName: "TWITCH.TV/LOLESPORTS_AR",
    twitchUrl: "https://www.twitch.tv/lolesports_ar",
  },
  {
    id: 8,
    team1: "/GNG.png",
    team2: "/foxgaming.png",
    game: "/lol.png",
    gameName: "lol",
    time: "13 june , 8pm (GMT+1)",
    twitchName: "TWITCH.TV/LOLESPORTS_AR",
    twitchUrl: "https://www.twitch.tv/lolesports_ar",
  },

];
